version: '3.8'

services:
  backend:
    build: ./back_agroconnect
    container_name: agroconnect-backend
    restart: always
    env_file:
      - ./back_agroconnect/.env
    ports:
      - "8000:8000"

  frontend:
    build: ./front_agroconnect
    container_name: agroconnect-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
 