"""Init models

Revision ID: 240584a27294
Revises: 
Create Date: 2026-04-13 02:50:45.831584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '240584a27294'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('mot_de_pass', sa.String(), nullable=False),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'CLIENT', 'AGRICULTEUR', name='roleenum'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('administrateurs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('agriculteurs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('localisation', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('est_lu', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('commandes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date_commande', sa.Date(), nullable=False),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'VALIDEE', 'ANNULEE', 'LIVREE', 'CONFIRMEE', name='statutenum'), nullable=False),
    sa.Column('montant_commande', sa.Float(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prix_unitaire', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('quantite_stock', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.Column('categorie', sa.Enum('LEGUME', 'CEREALE', 'FRUIT', name='categorieenum'), nullable=False),
    sa.Column('statut_publication', sa.Enum('EN_ATTENTE', 'PUBLIE', 'REJETE', name='statutpublicationenum'), nullable=False),
    sa.Column('agriculteur_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['agriculteur_id'], ['agriculteurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('details',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('commande_id', sa.String(), nullable=False),
    sa.Column('produit_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date_facture', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('moyen_paiement', sa.Enum('ORANGE_MONEY', 'WAVE', 'CARTE_BACAIRE', name='moyenpaiementenum'), nullable=True),
    sa.Column('commande_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commande_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factures')
    op.drop_table('details')
    op.drop_table('produits')
    op.drop_table('commandes')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('notifications')
    op.drop_table('clients')
    op.drop_table('agriculteurs')
    op.drop_table('administrateurs')
    op.drop_table('users')
    # ### end Alembic commands ###
