"""add_nom_to_produit

Revision ID: 7dd3377eb841
Revises: 0dc581ca7d27
Create Date: 2026-04-19 13:03:00.828831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd3377eb841'
down_revision: Union[str, None] = '0dc581ca7d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produits', sa.Column('nom', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produits', 'nom')
    # ### end Alembic commands ###
