"""Add photo to user

Revision ID: 8068d78e45fb
Revises: 240584a27294
Create Date: 2026-04-16 22:13:14.903917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8068d78e45fb'
down_revision: Union[str, None] = '240584a27294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agriculteurs', sa.Column('is_actif', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo')
    op.drop_column('agriculteurs', 'is_actif')
    # ### end Alembic commands ###
