name: Deploy AgroConnect

on:
  push:
    branches:
      - main

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.changes.outputs.frontend }}
      backend: ${{ steps.changes.outputs.backend }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend:
              - 'front_agroconnect/**'
            backend:
              - 'back_agroconnect/**'

  build-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Frontend Build Check
        run: |
          cd front_agroconnect
          npm install
          npm run build
          
      - name: Backend Syntax Check
        run: |
          cd back_agroconnect
          python3 -m compileall .

  deploy-frontend:
    needs: [filter, build-check]
    if: needs.filter.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy to Vercel
        run: |
          vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes --name plateformeagricole --cwd ./front_agroconnect

  deploy-backend:
    needs: [filter, build-check]
    if: needs.filter.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
